### PR TITLE
caf/LA.BR.1.2.9_rb.1.11

### PR DESCRIPTION
**Pull request by karthick111**

### CODE REVIEW

**Comment by karthick111** [comment]
@skritchz

**Comment by danielstuart14** [comment]
@karthick111 defconfig should be lineage_k5_defconfig. (As all lineage's kernels.)

Except from that, it seems nice. Good job, mate. :D

**Comment by skritchz** [comment]
@danielstuart14 
You didn't read my comment on your kernel branch.  https://github.com/AQSD/android_kernel_lenovo_msm8916/commit/54a4ed91a1df08e1a78538771336b26d67de56c8

The kernel doesn't have to include the "lineage_" in it's defconfig. Checkout motorola's kernel for instance. Moreover there was a discussion about this when going from cm -> lineage, all kernel's defconfig for devices using this naming had to be modified even though nothing had changed. 

I actually asked on the lineage slack and I'll paste rewrite the answer here

**Comment by skritchz** [comment]
Ok so answer is: actually it's not lineage_ but lineageos_ and we can do as follow:

> devicename_defconfig or lineageos_devicename_defconfig

I would rather go with the first one A6020_defconfig

**Comment by karthick111** [comment]
lineage_devicename_defconfig seems okay

**Comment by scritch007** [comment]
**lineageos_devicename_defconfig**
Actually kernel is used by other roms, why enforce the lineageos_

**Comment by karthick111** [comment]
@skritchz removed the rebranding of defconfig

**Pull request merged**
