### PR TITLE
Update the Linux Base Version (3.10.49--->3.10.105)

### PR DESCRIPTION
**Pull request by netship69**
@skritchz @danielstuart14 @Shr3ps

### CODE REVIEW

**Comment by Shr3ps** [comment]
Why did you squash the commits ? Did you use a CAF tag ?

**Comment by netship69** [comment]
Gavin gou squashed it(there were hundreds of commits).., i have just cherry-picked , fixed merge conflicts and compilation errors.

**Comment by danielstuart14** [comment]
Maybe we should merge caf BR1.2.9_rb1.12 before merging linux-3.10.y mainstream.
Would be easier to merge caf commits.

**Comment by netship69** [comment]
@Shr3ps

**Comment by netship69** [comment]
@danielstuart14 @Shr3ps @skritchz

**Comment by Shr3ps** [comment]
Thx for the commit history update & CAF rebase
This PR will wait a little, we need to froze the repos because https://github.com/LineageOS/android_kernel_lenovo_msm8916 is in sync

**Comment by netship69** [comment]
@Shr3ps 0_o

**Comment by Shr3ps** [comment]
@netship69 can you rebase? This PR might be merged if working fine.

**Comment by netship69** [comment]
I am busy with exams.. i will see this after 12 April..

**Pull request closed without merging**
